/**
  ******************************************************************************
  * @file
  * @author
  * @version
  * @date
  * @brief
  * @function List:
  ******************************************************************************
  * @attention
  *
  *
  * <h2><center>&copy; COPYRIGHT 2021 </center></h2>
  ******************************************************************************
  * @History:
  * @Author:
  * @Data:
  * @Version:
*/

#ifndef NVIC_CFG_H__
#define NVIC_CFG_H__




#define CPU_CFG_KA_IPL_BOUNDARY_11x  0
/*÷–î‡Éûœ»ºâ≈‰÷√*/
/*RCC*/
#define NVIC_PRIORITY_CLK   CPU_CFG_KA_IPL_BOUNDARY_11x
/*RTC*/
#define NVIC_PRIORITY_RTC   CPU_CFG_KA_IPL_BOUNDARY_11x
#define NVIC_PRIORITY_RTC_ALARM   CPU_CFG_KA_IPL_BOUNDARY_11x
//PDB0
#define NVIC_PRIORITY_PDB0   CPU_CFG_KA_IPL_BOUNDARY_11x
#define NVIC_PRIORITY_PDB1   CPU_CFG_KA_IPL_BOUNDARY_11x

#define NVIC_PRIORITY_WDOG   CPU_CFG_KA_IPL_BOUNDARY_11x
#define NVIC_PRIORITY_PVD   CPU_CFG_KA_IPL_BOUNDARY_11x
#define NVIC_PRIORITY_LPTMR   (CPU_CFG_KA_IPL_BOUNDARY_11x+1)

/*tim1 up*/
#define NVIC_PRIORITY_TIM0_UP   (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_TIM1_UP   (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_TIM2_UP   (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_TIM3_UP   (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_TIM4_UP   (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_TIM5_UP   (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_TIM6_UP   (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_TIM7_UP   (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_TIM8_UP   (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_TIM9_UP   (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_TIM10_UP   (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_TIM11_UP   (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_TIM12_UP   (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_TIM13_UP   (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_TIM14_UP   (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_TIM15_UP   (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_TIM16_UP   (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_TIM17_UP   (CPU_CFG_KA_IPL_BOUNDARY_11x+1)

#define NVIC_PRIORITY_TIM1_CC   (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_TIM2   (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_TIM3   (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_TIM4   (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_TIM5   (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_SPI1   (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_TIM10  (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_TIM0  (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_TIM1  (CPU_CFG_KA_IPL_BOUNDARY_11x+1)

#if 1
#define NVIC_PRIORITY_FLEXIO_LIN   (CPU_CFG_KA_IPL_BOUNDARY_11x+3)
#define NVIC_PRIORITY_USART1   (CPU_CFG_KA_IPL_BOUNDARY_11x+3)
#define NVIC_PRIORITY_USART2   (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_USART3   (CPU_CFG_KA_IPL_BOUNDARY_11x+0)
#define NVIC_PRIORITY_USART4   (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_USART5   (CPU_CFG_KA_IPL_BOUNDARY_11x+2)

#define NVIC_PRIORITY_DMA_USART1   NVIC_PRIORITY_USART1
#define NVIC_PRIORITY_DMA_USART2   NVIC_PRIORITY_USART2
#define NVIC_PRIORITY_DMA_USART3   NVIC_PRIORITY_USART3
#define NVIC_PRIORITY_DMA_USART4   NVIC_PRIORITY_USART4
#else

#define NVIC_PRIORITY_LOGIC_USART1   2u
#define NVIC_PRIORITY_LOGIC_USART2   5u
#define NVIC_PRIORITY_LOGIC_USART3   4u
#define NVIC_PRIORITY_LOGIC_USART4   3u
#define NVIC_PRIORITY_LOGIC_USART5   4u

#define NVIC_PRIORITY_LOGIC_DMA_USART1   2u
#define NVIC_PRIORITY_LOGIC_DMA_USART2   5u
#define NVIC_PRIORITY_LOGIC_DMA_USART3   4u
#define NVIC_PRIORITY_LOGIC_DMA_USART4   3u

#endif

#define NVIC_PRIORITY_FTFC   (CPU_CFG_KA_IPL_BOUNDARY_11x+3)

#define NVIC_PRIORITY_DMA0   (CPU_CFG_KA_IPL_BOUNDARY_11x+3)
#define NVIC_PRIORITY_DMA1   (CPU_CFG_KA_IPL_BOUNDARY_11x+3)
#define NVIC_PRIORITY_DMA2   (CPU_CFG_KA_IPL_BOUNDARY_11x+3)
#define NVIC_PRIORITY_DMA_ERROR   (CPU_CFG_KA_IPL_BOUNDARY_11x+3)


#define NVIC_PRIORITY_ADC0   (CPU_CFG_KA_IPL_BOUNDARY_11x+3)
#define NVIC_PRIORITY_ADC1   (CPU_CFG_KA_IPL_BOUNDARY_11x+3)
#define NVIC_PRIORITY_ADC2   (CPU_CFG_KA_IPL_BOUNDARY_11x+3)
#define NVIC_PRIORITY_ADC3   (CPU_CFG_KA_IPL_BOUNDARY_11x+3)

#define NVIC_PRIORITY_EXTI_SBC  (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_EXTI0  (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_EXTI1  (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_EXTI2  (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_EXTI3  (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_EXTI4  (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_EXTI5  (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_EXTI6  (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_EXTI7  (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_EXTI8  (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_EXTI9  (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_EXTI10  (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_EXTI11  (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_EXTI12  (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_EXTI13  (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_EXTI14  (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_EXTI15  (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_EXTI16  (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_EXTI17  (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_EXTI18 (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_EXTI19  (CPU_CFG_KA_IPL_BOUNDARY_11x+1)

#define NVIC_PRIORITY_CAN1_TX   (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_CAN1_RX0   (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_CAN0_RX0   (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_CAN1_RX1   (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_CAN1_SCE   (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_CAN2_TX   (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_CAN2_RX0   (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_CAN2_RX1   (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_CAN2_SCE   (CPU_CFG_KA_IPL_BOUNDARY_11x+1)

#define NVIC_PRIORITY_I2CEEPROM_TX1  (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_I2CEEPROM_RX1   (CPU_CFG_KA_IPL_BOUNDARY_11x+1)

#define NVIC_PRIORITY_USB_OTG   (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_USB_NORMAL   (CPU_CFG_KA_IPL_BOUNDARY_11x+1)
#define NVIC_PRIORITY_LPIT   (CPU_CFG_KA_IPL_BOUNDARY_11x+1)

#define NVIC_PRIORITY_RANDOM   (CPU_CFG_KA_IPL_BOUNDARY_11x+1)





#endif